import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        // Company 1 (USA) - USD
        {
            companyId: 1,
            userId: 1,
            amount: 1250.00,
            currency: 'USD',
            amountInCompanyCurrency: 1250.00,
            category: 'Travel',
            description: 'Flight tickets to San Francisco for client meeting',
            expenseDate: new Date('2024-10-15').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/flight-sf-oct2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-16').toISOString(),
        },
        {
            companyId: 1,
            userId: 2,
            amount: 1800.00,
            currency: 'USD',
            amountInCompanyCurrency: 1800.00,
            category: 'Travel',
            description: 'Hotel accommodation and car rental for Boston conference',
            expenseDate: new Date('2024-09-22').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/boston-hotel-sep2024.pdf',
            status: 'pending',
            createdAt: new Date('2024-09-25').toISOString(),
        },
        {
            companyId: 1,
            userId: 3,
            amount: 650.00,
            currency: 'USD',
            amountInCompanyCurrency: 650.00,
            category: 'Travel',
            description: 'Train tickets and meals for New York business trip',
            expenseDate: new Date('2024-11-05').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'rejected',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            companyId: 1,
            userId: 1,
            amount: 85.50,
            currency: 'USD',
            amountInCompanyCurrency: 85.50,
            category: 'Food',
            description: 'Team lunch at Italian restaurant',
            expenseDate: new Date('2024-11-12').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/team-lunch-nov2024.jpg',
            status: 'approved',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            companyId: 1,
            userId: 4,
            amount: 150.00,
            currency: 'USD',
            amountInCompanyCurrency: 150.00,
            category: 'Food',
            description: 'Client dinner at steakhouse',
            expenseDate: new Date('2024-10-28').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/client-dinner-oct2024.pdf',
            status: 'pending',
            createdAt: new Date('2024-10-29').toISOString(),
        },
        {
            companyId: 1,
            userId: 2,
            amount: 65.75,
            currency: 'USD',
            amountInCompanyCurrency: 65.75,
            category: 'Food',
            description: 'Coffee and snacks for late work session',
            expenseDate: new Date('2024-11-08').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'approved',
            createdAt: new Date('2024-11-09').toISOString(),
        },
        {
            companyId: 1,
            userId: 3,
            amount: 275.00,
            currency: 'USD',
            amountInCompanyCurrency: 275.00,
            category: 'Office Supplies',
            description: 'Ergonomic keyboard and mouse set',
            expenseDate: new Date('2024-10-10').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/office-supplies-oct2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-11').toISOString(),
        },
        {
            companyId: 1,
            userId: 1,
            amount: 420.00,
            currency: 'USD',
            amountInCompanyCurrency: 420.00,
            category: 'Office Supplies',
            description: 'Whiteboard markers, folders, and printer paper',
            expenseDate: new Date('2024-09-15').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'pending',
            createdAt: new Date('2024-09-16').toISOString(),
        },
        {
            companyId: 1,
            userId: 4,
            amount: 180.00,
            currency: 'USD',
            amountInCompanyCurrency: 180.00,
            category: 'Office Supplies',
            description: 'Standing desk converter and cable management',
            expenseDate: new Date('2024-11-01').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/desk-supplies-nov2024.jpg',
            status: 'rejected',
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            companyId: 1,
            userId: 2,
            amount: 450.00,
            currency: 'USD',
            amountInCompanyCurrency: 450.00,
            category: 'Entertainment',
            description: 'Company holiday party venue and catering',
            expenseDate: new Date('2024-12-15').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/holiday-party-dec2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-12-16').toISOString(),
        },
        {
            companyId: 1,
            userId: 3,
            amount: 320.00,
            currency: 'USD',
            amountInCompanyCurrency: 320.00,
            category: 'Entertainment',
            description: 'Baseball game tickets for client entertainment',
            expenseDate: new Date('2024-08-20').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'pending',
            createdAt: new Date('2024-08-21').toISOString(),
        },
        {
            companyId: 1,
            userId: 1,
            amount: 680.00,
            currency: 'USD',
            amountInCompanyCurrency: 680.00,
            category: 'Entertainment',
            description: 'Team building escape room and dinner event',
            expenseDate: new Date('2024-10-05').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/team-building-oct2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-06').toISOString(),
        },

        // Company 2 (Germany) - EUR
        {
            companyId: 2,
            userId: 5,
            amount: 1062.50,
            currency: 'EUR',
            amountInCompanyCurrency: 1062.50,
            category: 'Travel',
            description: 'Flight to Munich for automotive industry conference',
            expenseDate: new Date('2024-10-20').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/munich-flight-oct2024.pdf',
            status: 'pending',
            createdAt: new Date('2024-10-21').toISOString(),
        },
        {
            companyId: 2,
            userId: 6,
            amount: 1530.00,
            currency: 'EUR',
            amountInCompanyCurrency: 1530.00,
            category: 'Travel',
            description: 'Business trip to Frankfurt - hotel and transport',
            expenseDate: new Date('2024-09-30').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/frankfurt-trip-sep2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-01').toISOString(),
        },
        {
            companyId: 2,
            userId: 7,
            amount: 552.50,
            currency: 'EUR',
            amountInCompanyCurrency: 552.50,
            category: 'Travel',
            description: 'Train tickets to Berlin for supplier meeting',
            expenseDate: new Date('2024-11-18').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'rejected',
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            companyId: 2,
            userId: 8,
            amount: 72.25,
            currency: 'EUR',
            amountInCompanyCurrency: 72.25,
            category: 'Food',
            description: 'Working lunch with engineering team',
            expenseDate: new Date('2024-11-10').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/team-lunch-berlin-nov2024.jpg',
            status: 'approved',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            companyId: 2,
            userId: 5,
            amount: 127.50,
            currency: 'EUR',
            amountInCompanyCurrency: 127.50,
            category: 'Food',
            description: 'Business dinner with potential investors',
            expenseDate: new Date('2024-10-25').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/investor-dinner-oct2024.pdf',
            status: 'pending',
            createdAt: new Date('2024-10-26').toISOString(),
        },
        {
            companyId: 2,
            userId: 6,
            amount: 55.90,
            currency: 'EUR',
            amountInCompanyCurrency: 55.90,
            category: 'Food',
            description: 'Breakfast meeting at hotel restaurant',
            expenseDate: new Date('2024-11-03').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'approved',
            createdAt: new Date('2024-11-04').toISOString(),
        },
        {
            companyId: 2,
            userId: 7,
            amount: 233.75,
            currency: 'EUR',
            amountInCompanyCurrency: 233.75,
            category: 'Office Supplies',
            description: 'Wireless presentation clicker and laser pointer',
            expenseDate: new Date('2024-10-12').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/presentation-tools-oct2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-13').toISOString(),
        },
        {
            companyId: 2,
            userId: 8,
            amount: 357.00,
            currency: 'EUR',
            amountInCompanyCurrency: 357.00,
            category: 'Office Supplies',
            description: 'Monitor stand and desk organizers',
            expenseDate: new Date('2024-09-18').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'pending',
            createdAt: new Date('2024-09-19').toISOString(),
        },
        {
            companyId: 2,
            userId: 5,
            amount: 153.00,
            currency: 'EUR',
            amountInCompanyCurrency: 153.00,
            category: 'Office Supplies',
            description: 'Notebook computers and charging cables',
            expenseDate: new Date('2024-11-07').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/office-electronics-nov2024.jpg',
            status: 'rejected',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            companyId: 2,
            userId: 6,
            amount: 382.50,
            currency: 'EUR',
            amountInCompanyCurrency: 382.50,
            category: 'Entertainment',
            description: 'Oktoberfest company outing and traditional dinner',
            expenseDate: new Date('2024-09-28').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/oktoberfest-company-sep2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-09-29').toISOString(),
        },
        {
            companyId: 2,
            userId: 7,
            amount: 272.00,
            currency: 'EUR',
            amountInCompanyCurrency: 272.00,
            category: 'Entertainment',
            description: 'Opera tickets for client appreciation event',
            expenseDate: new Date('2024-10-14').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'pending',
            createdAt: new Date('2024-10-15').toISOString(),
        },
        {
            companyId: 2,
            userId: 8,
            amount: 578.00,
            currency: 'EUR',
            amountInCompanyCurrency: 578.00,
            category: 'Entertainment',
            description: 'Christmas market booth for company promotion',
            expenseDate: new Date('2024-12-10').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/christmas-market-dec2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-12-11').toISOString(),
        },

        // Company 3 (Japan) - JPY
        {
            companyId: 3,
            userId: 9,
            amount: 187500.00,
            currency: 'JPY',
            amountInCompanyCurrency: 187500.00,
            category: 'Travel',
            description: 'Shinkansen tickets to Osaka for technology summit',
            expenseDate: new Date('2024-10-18').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/osaka-shinkansen-oct2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-19').toISOString(),
        },
        {
            companyId: 3,
            userId: 10,
            amount: 270000.00,
            currency: 'JPY',
            amountInCompanyCurrency: 270000.00,
            category: 'Travel',
            description: 'International flight to Singapore for trade show',
            expenseDate: new Date('2024-09-12').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/singapore-flight-sep2024.pdf',
            status: 'pending',
            createdAt: new Date('2024-09-13').toISOString(),
        },
        {
            companyId: 3,
            userId: 11,
            amount: 97500.00,
            currency: 'JPY',
            amountInCompanyCurrency: 97500.00,
            category: 'Travel',
            description: 'Taxi and hotel expenses for Kyoto business meeting',
            expenseDate: new Date('2024-11-22').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'rejected',
            createdAt: new Date('2024-11-23').toISOString(),
        },
        {
            companyId: 3,
            userId: 12,
            amount: 12825.00,
            currency: 'JPY',
            amountInCompanyCurrency: 12825.00,
            category: 'Food',
            description: 'Sushi lunch meeting with vendor representatives',
            expenseDate: new Date('2024-11-15').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/sushi-lunch-nov2024.jpg',
            status: 'approved',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            companyId: 3,
            userId: 9,
            amount: 22500.00,
            currency: 'JPY',
            amountInCompanyCurrency: 22500.00,
            category: 'Food',
            description: 'Kaiseki dinner with international clients',
            expenseDate: new Date('2024-10-30').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/kaiseki-dinner-oct2024.pdf',
            status: 'pending',
            createdAt: new Date('2024-10-31').toISOString(),
        },
        {
            companyId: 3,
            userId: 10,
            amount: 9862.50,
            currency: 'JPY',
            amountInCompanyCurrency: 9862.50,
            category: 'Food',
            description: 'Bento boxes and tea for department meeting',
            expenseDate: new Date('2024-11-05').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'approved',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            companyId: 3,
            userId: 11,
            amount: 41250.00,
            currency: 'JPY',
            amountInCompanyCurrency: 41250.00,
            category: 'Office Supplies',
            description: 'Japanese calligraphy brushes and traditional paper',
            expenseDate: new Date('2024-10-08').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/calligraphy-supplies-oct2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-09').toISOString(),
        },
        {
            companyId: 3,
            userId: 12,
            amount: 63000.00,
            currency: 'JPY',
            amountInCompanyCurrency: 63000.00,
            category: 'Office Supplies',
            description: 'Tablet styluses and screen protectors',
            expenseDate: new Date('2024-09-20').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'pending',
            createdAt: new Date('2024-09-21').toISOString(),
        },
        {
            companyId: 3,
            userId: 9,
            amount: 27000.00,
            currency: 'JPY',
            amountInCompanyCurrency: 27000.00,
            category: 'Office Supplies',
            description: 'Ergonomic mouse pads and wrist rests',
            expenseDate: new Date('2024-11-12').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/ergonomic-supplies-nov2024.jpg',
            status: 'rejected',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            companyId: 3,
            userId: 10,
            amount: 67500.00,
            currency: 'JPY',
            amountInCompanyCurrency: 67500.00,
            category: 'Entertainment',
            description: 'Karaoke night for team building and bonding',
            expenseDate: new Date('2024-10-26').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/karaoke-team-oct2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-10-27').toISOString(),
        },
        {
            companyId: 3,
            userId: 11,
            amount: 48000.00,
            currency: 'JPY',
            amountInCompanyCurrency: 48000.00,
            category: 'Entertainment',
            description: 'Traditional tea ceremony for client relations',
            expenseDate: new Date('2024-09-08').toISOString().split('T')[0],
            receiptUrl: null,
            status: 'pending',
            createdAt: new Date('2024-09-09').toISOString(),
        },
        {
            companyId: 3,
            userId: 12,
            amount: 102000.00,
            currency: 'JPY',
            amountInCompanyCurrency: 102000.00,
            category: 'Entertainment',
            description: 'Cherry blossom viewing company picnic',
            expenseDate: new Date('2024-04-15').toISOString().split('T')[0],
            receiptUrl: 'https://receipts.example.com/cherry-blossom-apr2024.pdf',
            status: 'approved',
            createdAt: new Date('2024-04-16').toISOString(),
        }
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});